core/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT
from . import views
from controlcenter.views import controlcenter

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'admin/dashboard/', controlcenter.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^export/users/xls/$', views.export_users_xls, name='export_users_xls'),
    url(r'^export/catalog/xls/$', views.export_catalog_xls, name='export_catalog_xls'),
    url(r'^$', views.home_page, name='home_page'),
    url(r'', include('news.urls')),
    url(r'', include('catalog.urls')),
    url(r'', include('orders.urls')),
    url(r'', include('service.urls')),
]


if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

orders/models.py
from django.db import models
from django.utils import timezone
from catalog.models import Item

class Order(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя")
    phone = models.CharField(max_length=100, verbose_name="Телефон")
    category  = models.CharField(max_length=300, verbose_name="Категория", blank=True, null=True)
    topic = models.CharField(max_length=300, verbose_name="Тема", blank=True, null=True)
    note = models.TextField(max_length=300, verbose_name="Примечание", blank=True, null=True)
    processed = models.BooleanField(default=0, verbose_name="Принята")
    created_date = models.DateTimeField(default=timezone.now, verbose_name="Дата и время отправки")
    created_date_format = models.DateField(default=timezone.now, verbose_name="Дата отправки")


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_date']

    def __str__(self):
        return self.name + ' - ' + self.phone

templates/footer.html
        <section class="footer hero is-link">
            <div class="container">
                <div class="columns is-vcentered">
                    <div class="column is-5">
                        <p class="title">&laquo;Гомельагрокомплект&raquo;</p>
                        <p class="subtitle">К высокому качеству молока &mdash; вместе с нами!</p>
                    </div>
                    <div class="column is-3">
                        <p><a href="{% url 'news_list' %}">Новости предприятия</a></p>
                        <p><a href="{% url 'items_list' %}">Каталог продукции</a></p>
                        <p><a href="{% url 'service_list' %}">Предоставляемые услуги</a></p>
                        <p><a href="{% url 'home_page' %}#block-about">О предприятии</a></p>
                    </div>
                    <div class="column is-4">
                        <p>
                        247016, Республика Беларусь,<br/>
                        г. Гомель, а/г Ерёмино, ул. Сурганова, 14<br/>
                        Телефон: <a href="tel:+375232933666">+375 (232) 93-36-66</a>,<br/>
                        Факс: +375 (232) 93-36-40
                        </p>
                    </div>
                </div>
            </div>
        </section>

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>&laquo;Гомельагрокомплект&raquo;</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/libs/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.7.3/tiny-slider.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.7.3/min/tiny-slider.js"></script>

  </head>
  <body class="home-page">
    <nav id='js-navbar' class="navbar is-transparent">
      <div class="container">
        <div class="navbar-brand is-hidden-desktop">
          <a href="{% url 'home_page' %}" class="navbar-item no-hover is-tab" >
            <img src="{% static 'img/logo.png' %}" alt="Логотип ОАО Гомельагрокоплект" />
          </a>
            <div class="navbar-item navbar-brand-caption">
              <p>ОАО &laquo;Гомельагрокомплект&raquo;</p>
            </div>

            <div class="navbar-burger burger" data-target="main-menu">
              <span></span>
              <span></span>
              <span></span>
            </div>  
        </div>
        <div class="navbar-tabs navbar-menu" id="main-menu">
          <a class="navbar-item is-tab" href="#block-about">О предприятии</a>
          <a class="navbar-item is-tab" href="{% url 'news_list' %}">Новости</a>
          <a class="navbar-item is-tab" href="{% url 'items_list' %}">Продукция</a>
          <a class="navbar-item is-tab" href="{% url 'service_list' %}">Услуги</a>
          <a class="navbar-item is-tab" href="#block-contact">Контакты</a>
          {% if request.user.is_superuser %}
          <a class="navbar-item is-tab" href="{% url 'admin:index' %}"><i class="fa fa-lock"></i></a>
          {% endif %}
        </div>
        <div class="navbar-end">
          <div class="navbar-item navbar-name-logo">
            <img src="{% static 'img/logo.png' %}" style="margin-right: 1rem;"  alt="Логотип ОАО Гомельагрокоплект" />
            &laquo;Гомельагрокомплект&raquo;
          </div>
        </div>
      </div>
    </nav>
    <section id="section-header"  class="hero is-black is-large" >
      <div class="hero-body " >
        <div class="container">
          {% if title_text %}
          <h1 class="title is-2">{{ title_text.content }}</h1>
          {% else %}
          <h1 class="title is-2">Блок 'title' не задан</h1>
          {% endif %}
          {% if subtitle_text %}
          <h2 class="subtitle is-4">{{ subtitle_text.content }}</h2>
          {% else %}
          <h2 class="subtitle is-4">Блок 'subtitle' не задан</h2>
          {% endif %}
        </div>
      </div>
    </section>
    <section id="block-about" class="section" data-scroll>
      <div class="container">
        <h2 class="section-title title" >О предприятии</h2>
        <div class="columns">
          <div class="column is-6" >
            {% if images_about.count > 1 %}
              <div class='carousel-container-1'>
                {% for image in images_about %}
                <div class="custom-figure">
                    <img class="is-background" src="{{ image.source.url }}" alt=""  >
                    <p class="caption">{{ image.description }}</p>
                </div>
                {% endfor %}
              </div>
            {% else %}
              <p>Изображений с группой 'about' не найдено. Для работы галереи необходимо минимум два изображения</p>
            {% endif %}
          </div>

          <div class="column is-6">
            <div class="content">
              {% if about_text %}
              {% if about_text.is_extend %}
                {{ about_text.extend_content | safe }} 
              {% else %}
                {{ about_text.content }} 
              {% endif %}
              {% else  %}
                <p>Блок 'about' не задан</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="block-news" class="section" data-scroll>
      <div class="container">
        <h2 class="section-title title" >Новости</h2>
        <div class="news-cards">
          {% for item in news %}
          <div class="card">
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4">{{ item.title }}</p>
                  <p class="subtitle is-6">
                  {% for tag in item.tags.all %}
                    <a href="{{ tag.get_absolute_url }}">#{{ tag.title }}</a> 
                  {% endfor %}
                  </p>
                </div>
              </div>

              <div class="content">
                <div class="card-text">
                  {{ item.content | safe  }}
                </div>
                <div class="">
                  <time datetime="2016-1-1">{{ item.created_date | date:"SHORT_DATE_FORMAT" }}</time>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    <section id="block-friends" class="section notification" data-scroll>
      <div class="container">
        <h2 class="section-title title" >Наши друзья</h2>
        {% if images_friends.count > 3 %}
          <div class='carousel-container-2'>
            {% for image in images_friends %}
              {% if image.href %}
              <a target="_blank" href="{{ image.href }}">
                <img src="{{ image.source.url }}" alt="{{ image.title }}">
              </a>
              {% else %}
              <div>
                <img src="{{ image.source.url }}" alt="{{ image.title }}">
              </div>
              {% endif %}
            {% endfor %}
          </div>
        {% else %}
          <p>Изображения с группой 'friends' не найдены. Для работы слайдера необходимо минимум 4 изображения.</p>
        {% endif %}
      </div>
    </section>
    <section id="block-contact" class="section"  data-scroll>
      <div class="container">
        <h2 class="section-title title">Контакты</h2>
        <div class="columns">
          <div class="column is-6-desktop">
            <div class="content">
              <h4 class="title is-4 has-text-centered has-text-weight-bold" >
                Краткая информация
              </h4>
                {% if contact_text %}
                {% if contact_text.is_extend %}
                  {{ contact_text.extend_content | safe  }} 
                {% else %}
                  {{ contact_text.content }} 
                {% endif %}
                {% else  %}
                <p class="text-center text-bold">Блок 'contact' не задан</p>
                {% endif %}
            </div>
          </div>
          <div class="column is-6-desktop form-for-user">
            <h4 class="title is-4 text-center">Форма обращения граждан</h4>
            <form method="POST" class="js-form js-no-display columns is-multiline" id="order-form" action="{% url 'get_order_form' %}">
              {% csrf_token %}
              <input id="id_category" name="category" value="Обращения граждан" type="hidden">

              <div class="column is-6 field">
                <label class="label" for="id_name">Имя</label>
                <div class="control">
                  <input class="input" id="id_name" maxlength="100" name="name" required="" type="text">
                </div>
              </div>
              <div class="column is-6 field">
                <label class="label" for="id_phone">Телефон</label>
                <div class="control">
                  <input class="input js-phone-mask" id="id_phone" maxlength="100" name="phone" pattern=".{19}" required="" type="text">
                </div>
              </div>
              <div class="column is-12 field">
                <label class="label" for="id_topic">Тема обращения</label>
                <div class="control">
                  <input class="input" id="id_topic" maxlength="100" name="topic" required="" type="text">
                </div>
              </div>
              <div class="column is-12">
                <div class="field">
                  <label class="label" for="id_note">Обращения</label>
                  <div class="control">
                    <textarea class="textarea" cols="40" id="id_note" maxlength="300" name="note" rows="5"></textarea>
                  </div>
                </div>
                <div class="has-text-centered field is-grouped">
                  <div class="control">
                    <button class="button is-link">Отправить</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>

      </div>
    </section>

    {% include 'footer.html' %}


    <script src="{% static 'js/libs/imask.min.js' %}"></script>
    <!-- <script src="{% static 'js/libs/ScrollTrigger.min.js' %}"></script> -->
    <script src="{% static 'js/script.js' %}"></script>
    <script>
    var about_slider = tns({
      container: '.carousel-container-1',
      items: 1,
      slideBy: 1,
      controls: false,
      autoplay: true,
      nav: false,
      speed: 500,
      autoplayButtonOutput: false,
      autoplayTimeout: 7500,
    });
    var slider = tns({
      container: '.carousel-container-2',
      items: 1,
      slideBy: 1,
      controls: false,
      autoplay: true,
      nav: false,
      speed: 500,
      autoplayButtonOutput: false,
      loop: true,
      responsive: {
        540: {
          items: 1
        },
        700: {
          items: 2
        },
        900: {
          items: 3
        },
        1100: {
          items: 4
        }
      }

    });
    </script>
  </body>
</html>